spring:
  application:
    name: booksy
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

booksy:
  loyalty:
    loyaltyEnabled: true
    maxWithdrawThreshold: 10
  jobs:
    #book-cleanup-cron: "0 0 2 * * ?" - daily at 2 am
    book-cleanup-cron: "0 * * * * *"
    book-cleanup-threshold-days: 180
